### ISSUE TITLE
Feature: Develop the Hero section card

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#1]
## Description
Develop the Hero section card as per the designs

## Tasks
- [x] Develop the Hero section card as per the designs
- [x] Make sure the component is mobile-responsive
- [x] Write tests for your component and make sure they are passing before creating a PR

### Screenshots
![Screenshot 2024-08-08 130702](https://github.com/user-attachments/assets/52226acf-5d8b-46ed-8165-7af41f2213e5)
