### ISSUE TITLE
Feature: Develop the support Diani Children content section

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#15]
## Description
Develop the support Diani Children content sections according to the design.

## Tasks
- [ ] Develop the support Diani Childres content section as per designs
- [ ] Make sure the components are responsive on all screen sizes
- [ ] Write tests for the components you develop 

## Screenshots
![Screenshot 2024-09-16 111052](https://github.com/user-attachments/assets/4f965a40-20d2-4239-8a25-63441356d99b)
