### ISSUE TITLE
Feature: Develop the About Us page

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#16]
## Description
Develop the About Us page as per the Figma design.

## Tasks 
- [x] Develop the "About us" page as per the Figma designs
- [x] Make sure the page is fully responsive on all screen sizes
- [x] Write tests for the components you develop

## Screenshots
![Screenshot 2024-08-13 143308](https://github.com/user-attachments/assets/b510b2c7-1288-4b93-818f-606334384876)
