### ISSUE TITLE
Feature: Develop the Projects page as per the designs

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#17]
## Description
Develop the "Projects page" as per the designs

## Tasks 
- [ ] Develop the "Projects page" as per the designs
- [ ] Make sure the page is fully responsive on all screen sizes
- [ ] Write tests for the components you develop

![Screenshot 2024-08-13 143921](https://github.com/user-attachments/assets/13930016-bfdc-4537-8622-e56947a4e0f7)
