### ISSUE TITLE
Feature: Develop the "Meet the Children" page

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#18]
## Description
Develop the "Meet the Children" page as per the designs

## Tasks
- [ ] Develop the "Meet the Children" page as per the designs
- [ ] Make sure the page is fully responsive on all screen sizes
- [ ] Write unit tests for the components that you write

![Screenshot 2024-08-13 144319](https://github.com/user-attachments/assets/12cd00a0-fcd7-476a-b66d-8a3da47b2b1d)
