### ISSUE TITLE
Feature: Develop the "Meet the Team" page

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#19]
## Description
Develop the "Meet the team"page as per the designs

## Tasks
- [ ] Develop the "Meet the Team" page as per the designs
- [ ] Make sure the page is fully responsive
- [ ] Write tests for the components you develop

![Screenshot 2024-08-13 144626](https://github.com/user-attachments/assets/27c07af8-3db1-4a18-95f9-00b6b45d0db6)
