### ISSUE TITLE
Feature: Develop the navigation bar

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#2]
## Description
Develop the Navigation bar as per the Figma designs

## Tasks
- [ ] Develop the Navbar as per the Figma designs
- [ ] Make sure the component is fully responsive
- [ ] Write tests unit tests to test the components' look, feel, and functionality

### Screenshots
![Screenshot 2024-08-08 131157](https://github.com/user-attachments/assets/fc628a3c-874d-411b-a3b3-cf8a141d496b)
