### ISSUE TITLE
Feature: Develop the "Donate" page as per the designs

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#20]
## Description
Develop the "Donate page" as per the Figma design

## Tasks
- [x] Develop the "Donate" page as per the design
- [x] Make sure the page is fully responsive
- [x] Write tests for the components you develop

![Screenshot 2024-08-13 144959](https://github.com/user-attachments/assets/c28eed58-acde-40b0-a96a-6bcaac49bc59)
