### ISSUE TITLE
Feature: Develop the "Contact Us" page as per the designs

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#21]
## Description
Develop the "Contact us" page as per the Figma design.

## Tasks
- [ ] Develop the "Contact Us" page as per the designs
- [ ] Make sure the page is fully responsive
- [ ] Write tests for the components you develop

![Screenshot 2024-08-13 145250](https://github.com/user-attachments/assets/d4600867-5e42-4e45-99c4-065fa0870e88)
