### ISSUE TITLE
Feature: Finish developing the header section

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#29]
## Description
Finish developing the header section as per the designs

## Tasks
- [ ] Develop the header section to completion
- [ ] Make sure the section is fully mobile-responsive
- [ ] Write unit tests for the components you develop

![Screenshot 2024-08-19 091618](https://github.com/user-attachments/assets/8bcd7e04-2615-4f6a-8978-2c4a68e9a219)
