### ISSUE TITLE
Feature: Develop the News Alert section

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#3]
## Description
Develop the News Alert section as per the designs

## Tasks
- [ ] Develop the "News Alert" section as per the designs
- [ ] Ensure the components are fully responsive on all screen sizes
-  [ ] Write unit tests to test the look, feel, and functionality of the components

### Screenshots
![Screenshot 2024-08-08 131545](https://github.com/user-attachments/assets/c29984f5-40c5-41b1-8758-23e53afc01f9)
