### ISSUE TITLE
Feature: Develop the Graduation section and the Gallery section

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#6]
## Description
Develop the Gradation section and the Gallery section according to the designs provided. The pages should be fully responsive and functional

## Tasks
- [ ] Develop the Graduation section
- [ ] Develop the Gallery section
- [ ] Make sure the pages are fully responsive on all devices
- [ ] Write unit test for all the sections

### Screenshots
![Screenshot 2024-08-09 072827](https://github.com/user-attachments/assets/d5645f25-5faf-4c4e-add0-6f185bedc106)
