### ISSUE TITLE
Feature: Develop the Testimonial section

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#7]
## Description
Develop the testimonial section as per the designs. Make sure the section is fully responsive as well.

## Tasks
- [ ] Develop the testimonials section as per the designs
- [ ] Make sure the section is fully responsive
- [ ] Write unit tests for the components 

### Screenshots
![Screenshot 2024-08-09 081938](https://github.com/user-attachments/assets/cc30497f-7d44-412f-85f5-82ce68e91591)
