### ISSUE TITLE
Feature: Develop the Donate and footer section

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/DCV-Frontend#8]
## Description
Develop the donate and footer sections as per the designs provided

## Tasks
- [ ] Develop the footer and donate sections as per the designs
- [ ] Make sure the pages are fully responsive
- [ ] Write unit tests for the components you develop

### Screenshots
![Screenshot 2024-08-09 082310](https://github.com/user-attachments/assets/f920750d-f3a1-48d7-a933-ae3eb61489e1)
